# Generated by Django 5.0.7 on 2024-07-17 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rules_delete_houserules'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rules',
            new_name='Rule',
        ),
    ]
