# Generated by Django 5.0.7 on 2024-07-22 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_rules_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='subtext',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
