# Generated by Django 5.0.7 on 2024-08-01 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_information'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={},
        ),
        migrations.RemoveField(
            model_name='information',
            name='position',
        ),
    ]
