# Generated by Django 5.0.7 on 2024-08-02 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_information_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='subtext',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
