# Generated by Django 5.0.7 on 2024-08-11 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_information_subtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
