# Generated by Django 5.0.7 on 2024-08-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_information_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='image',
            field=models.ImageField(blank=True, upload_to='info_pics/'),
        ),
    ]
