# Generated by Django 5.0.7 on 2024-08-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_information_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='information',
            name='position',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
