# Generated by Django 5.0.7 on 2024-08-16 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_eats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eats',
            old_name='drive_distance',
            new_name='drive_time',
        ),
    ]
