# Generated by Django 5.0.7 on 2024-08-16 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_drive_distance_eats_drive_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='eats',
            name='image',
            field=models.ImageField(blank=True, upload_to='eats_pics/'),
        ),
    ]
