# Generated by Django 5.0.7 on 2024-08-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_eats_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('drive_time', models.IntegerField()),
                ('text', models.CharField(max_length=300)),
                ('website', models.CharField(blank=True, max_length=300)),
                ('position', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, upload_to='eats_pics/')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
