# Generated by Django 5.0.7 on 2024-08-16 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_activities'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activities',
            new_name='Activity',
        ),
    ]
