# Generated by Django 5.0.7 on 2024-08-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('html_content', models.TextField()),
            ],
        ),
    ]
