# Generated by Django 5.0.7 on 2024-08-23 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_activity_image_alter_eats_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='eats',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='information',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
